# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 250000
  #min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 0
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  train_subset: train_sp
  valid_subset: dev
  batch_size: 16

distributed_training:
  distributed_world_size: 1
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 10]

optimization:
  max_update: 200000
  lr: [0.0008]
  clip_norm: 0

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.1

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wav2vec2
  w2v_path: ???
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
  bottleneck_dim: ???
  use_first_adapter: ???
  adapter_before_quant: ???
  freeze_adapter: ???
  freeze_backbone: ???
  no_pretrained_weights: ???
  pretrained_weights_path: ???
  

